services:
  backend:
    build: ./backend
    image: burhanuddin2005/wavelane-backend:latest
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
    restart: always

  frontend:
    build: ./frontend
    image: burhanuddin2005/wavelane-frontend:latest
    ports:
      - "80:80"
    restart: always

  admin:
    build: ./admin
    image: burhanuddin2005/wavelane-admin:latest
    ports:
      - "8080:80"
    restart: always